README.md

Stylistic edits, fixing some typos, making some sentences a little cleaner.

Improve the README text quality

---

README.md

Ref https://github.com/postcss/autoprefixer/commit/3b73c88009029ae56a9c47f766dd17398b438456

Readd back Prepros in tools

---

README.md

change callback's syntax to promise's.

fix typo error of sample code at section Outdated Prefixes

---

README.md

The current grunt example is wrong. The commit updates the example with correct use of loadNpmTasks.
Fixes #490

update grunt example

---

README.md

Fixed typo in browser options

---

test/cases/gradient.css
test/cases/gradient.out.css

Tests: Add test for gradients on new lines

---

lib/hacks/gradient.coffee
test/autoprefixer.coffee
test/cases/gradient-fix.css
test/cases/gradient-fix.out.css

Fix: range outbound bug

---

test/cases/supports.css
test/cases/supports.out.css

Added two test cases for support query
(Last case requires fix)
#568

Test cases for support

---

test/cases/supports.css
test/cases/supports.out.css

Test case for @supports animation-name and transition-timing-function or
statement.
Working as intended @ai and passing with flying colors! #568

Test @supports animation

---

data/prefixes.coffee
lib/hacks/fill-available.coffee
lib/hacks/pixelated.coffee
test/cases/intrinsic.css
test/cases/intrinsic.out.css

https://drafts.csswg.org/css-sizing/?c=M%3BO%3DD#valdef-width-fill
Before:
```css
a {
width: fill-available;
}
```
After:
```css
a {
width: fill;
}
```

Intrinsic & extrinsic sizing rename 'fill-available' to 'fill'

---

lib/hacks/gradient.coffee
test/cases/gradient.out.css

Repair unit conversion.

---

data/prefixes.coffee

As discussed in https://github.com/postcss/autoprefixer/issues/754, this PR exposes the feature name in the prefixes data.

Augment prefixes data with feature name

---

README.md

see https://github.com/postcss/autoprefixer/issues/762#issuecomment-276736803

add postcss-font-family-system-ui to FAQ section

---

data/prefixes.coffee

`font-kerning` should derive from `font-kerning.json`

Derive from font-kerning feature

---

README.md

Update link to Codekit

---

lib/declaration.js

Changes if/else structure (flips it) so early returns can be used and else can be removed.
Result: more readable, easier to follow

[Refactor] Removes redundant else structures

---

README.md

Neutrino is really nice and makes it easy to integrate postcss/autoprefixer

Link to Neutrino build tool integration in Readme

---

.gitignore
.npmignore
lib/autoprefixer.js
lib/browsers.js
package.json
test/autoprefixer.test.js

Code coverage
===
Before:
--
> 97.12% Statements 2093/2155
> 92.69% Branches 1192/1286
> 97.45% Functions 382/392
> 97.23% Lines 2069/2128
After:
--
> 97.67% Statements 2099/2149
> 93.23% Branches 1199/1286
> 97.95% Functions 382/390
> 97.79% Lines 2075/2122

Add code coverage, tests of initializing and remove not used code

---

package.json
yarn.lock

Fix for IE 9/10 in class which use extends

---

lib/hacks/cross-fade.js
lib/hacks/flex.js
lib/prefixer.js
lib/prefixes.js
lib/transition.js
lib/utils.js
lib/value.js
test/at-rule.test.js
test/declaration.test.js
test/old-selector.test.js
test/prefixer.test.js
test/prefixes.test.js
test/selector.test.js
test/value.test.js

Don't require sub-files in postcss

---

lib/hacks/grid-utils.js
test/cases/grid-template-areas.css
test/cases/grid-template-areas.out.css
test/cases/grid-template.css
test/cases/grid-template.out.css

Problem is mentioned in the issues #954 #1016 and discussed in the issue #954

[grid-template-areas] Supported grid-template(-areas) in media rules

---

README.md
lib/processor.js
test/autoprefixer.test.js
test/cases/ignore-next.css
test/cases/ignore-next.out.css

#1024 Added support for comment "autoprefixer: ignore next"

"autoprefixer: ignore next" support

---

lib/hacks/grid-utils.js
test/cases/grid-gap.css
test/cases/grid-gap.out.css
test/cases/grid-template.css
test/cases/grid-template.out.css

#1049 I added some additional checks so that row size would be defined as 'auto' if not specified.

Fix grid template parsing in case of auto row sizes

---

lib/hacks/grid-utils.js
test/cases/grid-gap.css
test/cases/grid-gap.out.css

* Support two values #1044 
* Support new `gap` property #1046

[css-grid] Grid-gap: two values, gap prop

---

lib/hacks/grid-utils.js
test/cases/grid-template-areas.css
test/cases/grid-template-areas.out.css
test/cases/grid-template.css
test/cases/grid-template.out.css

Third solution without duplication media queries.
Now we have solutions for all [3 decisions](https://github.com/postcss/autoprefixer/issues/1048#issuecomment-390410054) that we discussed 😄

[css-grid] move media query cell placements to come after cell styles

---

README.md

Update the description of `postcss-preset-env` in the README.md

---

lib/hacks/grid-template-areas.js
lib/hacks/grid-template.js
lib/hacks/grid-utils.js
package.json
test/cases/grid-gap.css
test/cases/grid-gap.out.css

 [grid-gap] retain gaps through media

---

lib/hacks/grid-utils.js
test/cases/grid-area-media-sequence.css
test/cases/grid-area-media-sequence.out.css
test/cases/grid-template.out.css

PR should fix this issue:  #1096 
@gisu Can you please try this forked version of autoprefixer to make sure the bug is fixed? You can install it like this:
```npm i --save-dev bogdan0083/autoprefixer#add-span-fix```
If the bug is fixed and everything is fine then we can merge :smile:

[css-grid] fix bug when searching areas

---

lib/hacks/grid-area.js
lib/hacks/grid-utils.js
test/autoprefixer.test.js
test/cases/grid-area.css
test/cases/grid-area.out.css

Fixes #1122
cc @Dan503 
Should we change warning message or we'll leave it like this?

[css-grid] Show warning if grid-area and grid-(row/column) both present in the same rule

---

lib/hacks/writing-mode.js
test/cases/writing-mode.css
test/cases/writing-mode.out.css

Add `ms-writing-mode` value based on `direction` declaration

---

lib/hacks/grid-utils.js
test/autoprefixer.test.js

I think there was a small typo: `impliment` instead of `implement`.

Fix 'implement' typo

---

README.md

Correct CodePen name

---

lib/hacks/file-selector-button.js
test/cases/file-selector-button.css
test/cases/file-selector-button.out.css

https://twitter.com/usmanyunusov

Fix ::file-selector-button pseudo-element

---

package.json
pnpm-lock.yaml
test/cases/example.out.css
test/cases/file-selector-button.out.css
test/cases/fullscreen.out.css
test/cases/keyframes.out.css
test/cases/placeholder-shown.out.css
test/cases/placeholder.out.css
test/cases/viewport.out.css

[PostCSS 8.4.17](https://github.com/postcss/postcss/releases/tag/8.4.17) contains a fix which affects whitespace in some cases.
Updating test files so that this isn't blocking for a future change.

update tests results for postcss 8.4.17

---

lib/processor.js
test/autoprefixer.test.js
test/cases/webkit-line-clamp.out.css

Preserve -webkit-box-orient when -webkit-line-clamp is present
