autoprefixer
This allows the process to exit gracefully and ensures all writes have finished flushing.
This addresses #437 and is probably a better solution.
=> Only hard process.exit when there's an error

README.md
Making consistent usage of 'versions' across README. Browserslist can recognize both, but only uses 'versions' in its documentation.
=> Consistently pluralize 'versions' to match Browserslist usage

lib/hacks/cross-fade.coffee, test/cases/cross-fade.css, test/cases/cross-fade.out.css
The old spec(-webkit-) support `<number>`(0.5, .5)
=> Fix cross-fade() not support `<number>`

README.md
Hi, just a small correction for a typo in README.md: "directiom" should be "direction".
Thanks,
Rob
=> Fixed typo: "directiom" should be "direction"

lib/supports.coffee
**Adding parenthesis to join so OR statements don’t conflict with nested conditions.** 
Fixes #568 
Meeting requirements from issue:
```
@supports ((perspective: 1px) and (not (-webkit-overflow-scrolling: touch))){}
```
```
@supports (((-webkit-perspective: 1px) and (not (-webkit-overflow-scrolling: touch))) or ((perspective: 1px) and (not (-webkit-overflow-scrolling: touch)))){}
```
Basic example:
```
@supports (perspective: 1px){}
```
```
@supports (((-webkit-perspective: 1px)) or ((perspective: 1px))){}
```
not ( example ):
```
@supports not (display: flex){}
```
```
@supports not (((display: -webkit-box)) or ((display: -webkit-flex)) or ((display: -ms-flexbox)) or ((display: flex))){}
```
In cases where parenthesis are redundant 
http://www.w3.org/TR/css3-conditional/#at-supports …
=> Wrapping ( or )

lib/hacks/text-emphasis-position.coffee, test/cases/text-emphasis-position.css, test/cases/text-emphasis-position.out.css
Reverse value order 
input: 
```css
em {
text-emphasis-position: left over;
}
```
output:
```css
em {
-webkit-text-emphasis-position: over;
text-emphasis-position: left over;
}
```
=> Fix text-emphasis-position reverse value order

lib/transition.coffee
Found this error in angular-material library:
```
Cannot read property 'indexOf' of undefined
```
It happens for this code:
```
opacity: 1;
-webkit-transform: translate3d(0, 0, 0) rotateZ(0deg);
transform: translate3d(0, 0, 0) rotateZ(0deg);
transition: 0.2s linear;
transition-property: -webkit-transform, opacity;
transition-property: transform, opacity;
```
=> indexOf undefined

data/prefixes.coffee, lib/autoprefixer.coffee, lib/browsers.coffee, lib/supports.coffee, test/browsers.coffee, test/info.coffee, test/prefixes.coffee
It's bad practice to implicitly load files by name without specifying
their extension. This fix helps autoprefixer work more easily with
jspm's expectations of how files should be require'd.
This resolves #618 and also respects 80-char max line length.
=> Add .json file-ending to all relevant require statements

README.md
Links can't have same name and different URLs if you use reference text in Markdown. So because of this link to Ruby on Rails version had hash `#compass` in URL. Now it fixed.
=> Fix link to autoprefixer-rails

data/prefixes.coffee
Removing duplicate code. The feature was already included in the line 436.
=> Remove duplicate text-emphasis

AUTHORS, lib/hacks/flex.coffee, test/cases/flexbox.out.css
**Demo:** http://codepen.io/anon/pen/rWwaOZ
**Expected result (Chrome 55):** [Screenshot](https://cloud.githubusercontent.com/assets/79461/20585007/db4f10e8-b24b-11e6-9f89-ba120c2d28b4.png)
**Expected result (IE 11):** [Screenshot](https://cloud.githubusercontent.com/assets/79461/20585029/00e2101c-b24c-11e6-924e-15edc7ff5b6f.png)
**Overview:**
This is a workaround for [this IE10/11 bug](https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored).
Only applies when there are three components in the flex property.
This is because when there's one or two components only, it's ambiguous whether whether the first component being a unitless 0 is intended to be flex-grow or flex-basis. Browsers resolve this by treating such cases as a …
=> Hack for unitless 0 basis in IE10/IE11 shorthand flex

data/prefixes.coffee
For the sake of completeness and to make one more test pass on our way to make https://github.com/cssinjs/css-vendor comply with autoprefixer :-)
=> Add prefix to text-decoration-skip in IOS

data/prefixes.coffee
I think clip-path should derive from `caniuse-db/features-json/css-clip-path.json` instead of `caniuse-db/features-json/css-masks.json`.
This was a real quick patch. Please check for correctness.
=> Clip Path should derive from css-clip-path feature

README.md
The old example won't work in postcss-cli v3, since `--use` takes an array.
=> Fix postcss-cli usage

README.md
This reflects the change noted at the current (outdated) URL
=> Update PostCSS API URL

README.md
- Replace link of `postcss-unprefix` in `README.md`.
- Remove items that are not maintained:
- `postcss-flexboxfixer`
- `postcss-gradientfixer`
=> add link of `postcss-unprefix`

data/prefixes.js, lib/hacks/intrinsic.js, test/cases/intrinsic.css, test/cases/intrinsic.out.css
In CSS grid, only Safari needs to add the -webkit- prefix to min-content/max-content values.
Fixed this commit: https://github.com/postcss/autoprefixer/commit/99def371c9511212dfc9c1eaa573abfee813b97d?diff=split#diff-edefb210647f5ec99168718dbbf80320R36
and this issue: https://github.com/postcss/autoprefixer/issues/803
@ai
=> Fix: Do not add non-webkit prefixes for CSS grid

lib/resolution.js
Removes the else after the continue (inside a for loop).
Result: less indentation, less code, more readable, easier to follow
=> [Refactor] Removes redundant else structures

lib/hacks/gradient.js
When the same global regex object is used, you need to reset the lastIndex property. I have not yet looked at all the other hacks for additional occurrences of this bug.
Currently every other linear-gradient appearing in your css is converted into an invalid form.
Take `foo.css`
```css
.a {                                                                                                
background: linear-gradient(top,#fff 0,#ff3300 3%,#ff9900 100%);                                
}
#a {
background: #fff;
}
.b {                                                                                                
background: linear-gradient(top,#fff 0,#ff3300 3%,#ff9900 100%);                                
} 
.c { …
```
=> Bugfix reuse of global RegEx object.

lib/autoprefixer.js
Fixes https://github.com/postcss/autoprefixer/issues/931.
This provides a default file path when invoking the `info()` method on the plugin. This allows the plugin to, by default, retrieve the local config from the file system. If you pass a hash to `info`, then that will be used without modification.
=> Provide a default file path for info() output

data/prefixes.js, lib/hacks/grid-area.js, lib/hacks/grid-row-column.js, lib/hacks/grid-shorthand.js, lib/hacks/grid-start.js, lib/prefixes.js, package.json, test/autoprefixer.test.js, test/cases/grid-area.css, test/cases/grid-area.out.css, test/cases/grid.css, test/cases/grid.disabled.css, test/cases/grid.out.css
Another take on #883 
While the original issue suggested only translation of span syntax, this is an attempt to translate `grid-area` shorthand to `-ms-` properties as fully as possible. It is also applied to `grid-row` and `grid-column` shorthands.
~~Tests are failing:~~
~~1) 'removes unnecessary prefixes': presumably because it also should remove `-ms-` properties and currently it doesn't.~~
~~2) 'prevents doubling prefixes': it adds properties again.~~
~~Currently I'm trying to figure it out.~~
=> Add partial grid-area support, improve grid-row and grid-column

lib/hacks/animation.js
Array#some stops executing once it finds a matching element which makes the
code a little faster than using Array#forEach in some cases. It's also smaller.
Ref b8cbd673b81360214c3bb4d597b83639aca0027f
Ref ai/autoprefixer-rails#128
=> Reduce size & make animation check a little faster

README.md
Readme uses absolute counts which seem to be stale. `Features` section lists 3 options instead of 4 and the `Options` sections lists 9 instead of 8.
Absolute counts removed and the wording improved in terms of grammar.
=> Readme stale counts removed, wording improved

lib/processor.js, package.json, test/cases/gradient.css, test/cases/gradient.out.css
=> Look for outdated gradient syntax only inside radial-gradient block

lib/processor.js
If not do so, there are fatal errors, at least on my projects...
=> fix Processor.disabled(): check if node has parent before get prev()

lib/hacks/grid-rows-columns.js, lib/hacks/grid-template-areas.js, lib/hacks/grid-template.js, lib/hacks/grid-utils.js, package.json, test/autoprefixer.test.js, test/cases/grid-gap.css, test/cases/grid-gap.out.css, test/cases/grid.css, test/cases/grid.disabled.css, test/cases/grid.out.css
=> Add support for grid-gap

README.md
according to http://www.dictionary.com/e/practice-vs-practise/ since this is being used as a noun
it should be spelled with a `c` in both American and British English
=> fix(readme): Best Practises -> Best Practices

README.md
See: https://github.com/postcss/autoprefixer/issues/1074
=> Add a FAQ section for IE grid support caveats

lib/hacks/grid-area.js, lib/hacks/grid-template-areas.js, lib/hacks/grid-template.js, lib/hacks/grid-utils.js, test/autoprefixer.test.js, test/cases/grid-template.css, test/cases/grid-template.out.css
This is my first PR which adds warning when grid-area has a non-unique identifier (conflict of names). #1038
Not sure if code is clean enough, but I had a lot of fun working on this issue. Thanks! :)
Some questions:
* In my code I refer to area names in grid-area as "identifiers" ([see this](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident)). Is it alright?
* How should we handle grid-area inside media? I've omitted checking warnings inside media for now
=> Show warning if grid-area has a non-unique identifier (fixes #1038)

lib/hacks/grid-utils.js, test/cases/grid-template.out.css
This PR fixes #1084.
@Dan503 Can you please review grid-template.out.css in you spare time? I think now it should add -ms-grid-(row|column)-span just fine 👍
=> [grid-template] fix adding grid span for IE (fixes #1084)

README.md
=> docs: update babel-preset-env link

gulpfile.js, package.json, playground/playground.input.css, playground/playground.output.css, yarn.lock
It's been a massive pain trying to test whatever the current build of Autoprefixer is while it's been under development.
I've been resorting to opening the Autoprefixer repo, compiling it, copying the compiled assets into the node_modules folder of a completely unrelated project and then running the compiler for that project to get output CSS.
**That is an insane workflow!**
There needed to be an easier way to play around with the current Autoprefixer build and see if things are working as they are supposed to without having to go to all the trouble of creating formal tests.
So with that in mind I set up this simple little experimentation playground inside the Autoprefixer repo.
1. Run the command `gulp play`
2. Write some CSS in `playground.input.css` and save the file
3. View the output …
=> Adding a basic experimentation playground to the repo

README.md
Currently the readme links to an older version of the Visual Studio plugin, the new version of the project is WebCompiler, also by Mads Kristensen.
=> Update Visual Studio build tool link

lib/processor.js, package.json, test/autoprefixer.test.js, test/cases/grid.css, test/cases/grid.disabled.css, test/cases/grid.out.css
This is a branch off of https://github.com/postcss/autoprefixer/pull/1123 by @janczer.
It fixes https://github.com/postcss/autoprefixer/pull/1123 (`align/justify-items/content` warnings).
Our branches got out of sync and it was too difficult to merge them back together so I'm just making a new pull request instead.
Further discussion is in https://github.com/postcss/autoprefixer/pull/1123
=> [Updated] Add warning to align/justify-items/content in IE

README.md, lib/processor.js, test/autoprefixer.test.js, test/cases/grid-status.css, test/cases/grid-status.out.css
* Add gridStatus method to Processor
* Add test case
* Update README.md
=> Control grid option via comment

data/prefixes.js, lib/hacks/place-self.js, lib/prefixes.js, lib/processor.js, test/autoprefixer.test.js, test/cases/grid.css, test/cases/grid.disabled.css, test/cases/grid.out.css
Fixes #1143
The tests for this PR are failing because I need to find a way to make place-self hack to not add prefixes if css grid is disabled (described the problem [here](https://github.com/postcss/autoprefixer/issues/1143#issuecomment-430999451))
But the prefixes are being added correctly and can be tested 😀
/cc @Dan503
=> [css-grid] Implement hack for place-self property

lib/hacks/grid-utils.js, test/cases/grid.css, test/cases/grid.disabled.css, test/cases/grid.out.css
We discussed the bug here: #1148 
When `repeat` function were used with multiple values (e.g `repeat(1, 1fr 2fr)`) it output the wrong values.
Input: 
```css
.grid {
grid-template-columns: 50px repeat(2, 1fr 2fr) 50px;
grid-template-rows: repeat(1, auto 100px);
grid-gap: 20px;
grid-template-areas:
". . . . . ."
". . . . . .";
}
```
Before fix:
```css
.grid {
/* gaps are place wrongly and commas should not be here */
-ms-grid-columns: 50px 20px 1fr, ,2fr 20px 1fr, ,2fr 20px 50px;
grid-template-columns: 50px repeat(2, 1fr 2fr) 50px;
/* gaps are place wrongly and commas should not be here */
-ms-grid-rows: auto, ,100px;
grid-template-rows: repeat(1, auto 100px);
grid-gap: 20px;
grid-template-areas:
". . . . . ."
". . . . . .";
}
```
After fix:
```css
.grid {
-ms-grid-columns: 50px 20px 1fr …
```
=> [css-grid] Fix bug when grid-rows/columns are prefixed with wrong values

README.md
The previous recomendation of swapping the order around was wrong. The nth-child selector will still overpower the single class selector even if the single class selector comes after the nth-child selector.
Unfortunately this will need to be released as 9.4.1 if you want the readme fix to appear on npm. ☹
I tried bumping the package.json file myself but git refused to accept the commit.
=> Fixed enabling autoplacement in old projects section recommendation

lib/processor.js, test/autoprefixer.test.js
The values `start` and `end` for the properties `justify-content` and `align-content` has [mixed support in Flexbox layout](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#Support_in_Flex_layout) and behave the same as `flex-start` and `flex-end`. This PR warns the user the Flexbox specific value has better support and should be preferred.
Fixes: https://github.com/postcss/autoprefixer/issues/1170
=> Add warning for some content-distribution and alignement properties

gulpfile.js
There were some issues with the Gulp 4 code. This pull request fixes those issues.
- Replaced `path.join()` with a `join()` function (`path.join()` doesn't work properly in Gulp 4)
- It now runs `'build:lib'`, `'build:docs'`, `'build:bin'`, and `'build:package'` all in parallel rather than one after the other for a faster compile time.
- Replaced the old `gulp.start()` commands (not a valid syntax in Gulp 4) with proper `gulp.series()` syntax.
- Fixed the `"watch-playground"` Gulp task syntax.
=> Gulp 4 code fixes

test/autoprefixer.test.js
According to issue #1203 
Excludes '\r' symbol, tests compare uniform values of `output` and `result` variables.
=> Fix tests for OS Windows

data/prefixes.js
According to [caniuse data](https://caniuse.com/#search=backdrop-filter), this property should be prefixed with `-webkit-` in Edge 17/18.
Added proper match value to match Edge 17/18 values (`y #2`) properly.
=> Fix for backdrop-filter to support it properly in Edge 17/18

README.md
I've found that readme contains a dead link that probably should be removed
=> Removed dead link 'No prefixes in production'

README.md
The documentation now gives a step by step guide on how to use environment variables to turn on CSS Grid prefixing.
I've also added it to the table of contents.
=> Adding better environment variables documentation

README.md
It previously only explained how to support windows. It now also supports Mac and any other platform that [cross-env](https://www.npmjs.com/package/cross-env) supports.
New documentation is based on the comment by @Chun-Lin https://github.com/postcss/autoprefixer/issues/1257#issuecomment-549230805
I tested his suggestion on Windows and it seems to work.
=> Updating environment variable documentation to include multi-platform support

README.md
The PostCSS documentation has moved, and this link moved with it. I believe this is the new page for the `Warning` class. Thanks for the great library!
=> Fix link to PostCSS warning API docs

README.md
The linked project was abandoned. Linking to an actively maintained fork instead.
=> Update README.md grunt-postcss URL

lib/autoprefixer.js, package.json, test/webpack.test.js
Now uses the same, small color library as postcss (recently updated). 
Made sure to use the same `kleur/colors` variant so that the same file is loaded/reused.
You were surprisingly using `chalk@^2.4`, which is/was a different version than the `postcss@^7.0.30` range used, so users were juggling two copies of chalk in their dependency tree.
Performance numbers, comparing `kleur/colors` to `chalk@2.4`
```
chalk@2.4        x  12,373 ops/sec ±2.19%
kleur/colors     x 862,421 ops/sec ±0.19%
chalk@2.4        x   2,690 ops/sec ±2.32%
kleur/colors     x 103,509 ops/sec ±0.30%
chalk@2.4        x   5,882 ops/sec ±1.34%
kleur/colors     x 143,956 ops/sec ±0.25%
```
=> chore: swap color lib

lib/processor.js, playground/input.css, playground/output.css, test/autoprefixer.test.js, test/cases/grid.css, test/cases/grid.disabled.css, test/cases/grid.out.css
- Fixes #1333 - It no longer triggers grid warnings if `/* autoprefixer grid: off */` is used
- It will now warn that subgrid is not supported in IE if someone tries to use `subgrid` as a value in a declaration
- I added "npx" to the front of the "gulp play" command in the playground css comment to prevent people getting confused if they don't have gulp installed globally.
=> Fix for #1333 - No warnings when grid is turned off; Also added a subgrid warning

lib/processor.js, test/autoprefixer.test.js, test/cases/grid.css, test/cases/grid.disabled.css, test/cases/grid.out.css
=> Fix for issue #1335 justify/align self not prefixing if disply: flex

CHANGELOG.md
I'll need you to update the [release page for v9.8.5](https://github.com/postcss/autoprefixer/releases/tag/9.8.5).
Why have this change-log file anyway? Can't you just link to the [releases page in GitHub](https://github.com/postcss/autoprefixer/releases)?
=> Change log fix for v9.8.5

lib/utils.js
Simplify `uniq(array)` util with `Set` & spread syntax. All tests are passed.
`Set` is supported since Node.js 0.13 while spread syntax is fully supported since Node.js 8.3.0.
=> Simplify uniq util

lib/autoprefixer.js, lib/prefixes.js, lib/selector.js
`Map` provides methods like `get`, `set` & `has` that is more intuitive for caching.
Also, [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) suggests that:
> (Map) performs better in scenarios involving frequent additions and removals of key-value pairs, (while Object is) not optimized for frequent additions and removals of key-value pairs.
`Map` is supported since Node.js 0.12.0.
All tests are passed for the PR.
=> Refactor cache into Map

lib/hacks/mask-composite.js, test/cases/mask-composite.css, test/cases/mask-composite.out.css
Just changed "substract" to "subtract" so `mask-composite: subtract` outputs `-webkit-mask-composite: source-out`
=> fixed misspelling of "subtract" for mask-composite

lib/hacks/grid-utils.js
Hello!
Yesterday I tried to migrate https://aviasales.com to PostCSS 8 and Autoprefixer 10 and I found a problem, but I couldn't locate it. @ai show me the place, and I fix it.
https://github.com/postcss/postcss/pull/1473
I thinks, code of this PR is kind of dirty, maybe we should change `index()` method signature and return `-1`, if someone pass something unexpected (exactly as `Array#indexOf` works)?
Actually, I still can not reproduce this error in test-env (it is the reason, why I did not write any new tests), because I do not really understand how this case can be possible. I write this code like a monkey, sorry 🤣
=> Fix Cannot read property 'proxyOf' of undefined exception from PostCSS

lib/resolution.js, package.json, test/cases/resolution.css, test/cases/resolution.out.css, yarn.lock
I added dpcm support for resolution media queries and replaced num2fraction with Fraction.js, which does basically the same but uses Farey Sequences as rational approximation (more precise) and simplifies the fraction using continued fractions to ɛ <0.001 afterwards. 
Additional test cases were added as well.
=> Added dpcm resolution support and made calc more precise

.github/CONTRIBUTING.md
To make it easier for potential new contributors, I propose the following changes:
- fix logo src path: seems like a simple typo from copy-pasting from README.md that is in the parent folder, so I just added `../`
- code blocks indentation: seems like github flavored markdown needs a different indentation from the one that was used, i just used syntax highlighting to make sure github could parse the code blocks correctly.
=> fix CONTRIBUTING.md formatting

lib/autoprefixer.d.ts, package.json, test/autoprefixer.test.ts, tsconfig.json, yarn.lock
Add typings based on typings from DefinitelyTyped.
=> Add typings

lib/transition.js, test/autoprefixer.test.js, test/autoprefixer.test.ts, test/cases/transition-no-warning.css, test/cases/transition-no-warning.out.css
This PR answers the issue #1384 (and following discussion). It includes related tests and code comments.
=> check transition-property value list before warn

lib/supports.js, test/supports.test.js
=> Fix error throwing when `supports-selector-fn` has pseudo-classes or pseudo-elements as argument.

package.json
`postcss` from 7.0.0 and before 8.2.10 are vulnerable to Regular Expression Denial of Service (ReDoS) during source map parsing, as stated in this advisory: https://www.npmjs.com/advisories/1693 
This PR seeks to update the postcss package to a patched version.
=> update postcss to patched version

lib/autoprefixer.js
Due to user error or outdated scripts, users may be warned about no prefixes being applied.
Rewrite this error message to be more understandable.
This should help with #1318
=> Clarify warning about no targets

README.md
When you hit the link, it takes you to the Google developers page, but you can't find the referenced page, it looks like the setup/configuration section where they recommended using the autoprefixer has been removed.
[![Image from Gyazo](https://i.gyazo.com/9c15ca59cee871a062bf995ee8c0473f.png)](https://gyazo.com/9c15ca59cee871a062bf995ee8c0473f)
=> Fix: remove broken link with 404 error

lib/processor.js, test/autoprefixer.test.ts, test/cases/content.css, test/cases/content.out.css
=> Fix: Term element in content value gets parsed

package.json
Useful for contributors to quickly go to GitHub after they've cloned the repo.
Similar to how it's done at: https://github.com/postcss/postcss/blob/e2f59d057f30d419e8fa7fac0095d3a47795714d/package.json#L66
=> Add bugs field/URL to package.json

README.md
Without `postcss` fails with error:
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'postcss' `
=> Fix CLI dependency installation instructions

data/prefixes.js
This PR changes file-selector-button to pull data from caniuse-lite (which in turn generates it from MDN see https://github.com/browserslist/caniuse-lite/pull/90).
Previously this data was hardcoded but it seems I may have done this wrong originally, rather than trying to fix the hardcoded data it makes more sense to do what I did for the autofill data.
=> Use caniuse-lite data for `::file-selector-button`

package.json
Hi! I'm submitting this PR because in the [simple-icons](https://github.com/simple-icons/simple-icons) project we are trying to automate as much as possible our monetary contributions to our direct dependencies, so having this metadata in the package.json files allows us to programmatically know easily how we can fund them. The `funding` key in package.json accepts an array for all the ways for funding a package, see [package-json#funding](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#funding).
Cheers!
=> Update `funding` key in package.json

data/prefixes.js, test/autoprefixer.test.js, test/cases/text-decoration.out.css, test/cases/text-decoration.shorthand.out.css
Partial fix for the `text-decoration` issue.
This ensures that `text-decoration` will be prefixed even in current Safari versions.
It also updates the tests related to `text-decoration`
https://github.com/postcss/autoprefixer/issues/1473
----
I did my best to avoid conflicts with https://github.com/postcss/autoprefixer/pull/1474 as both are needed.
But it will be needed to rebase one of these and resolve conflicts.
=> update data for `text-decoration`

lib/hacks/gradient.js, test/cases/gradient.css, test/cases/gradient.out.css
Problems found during lightningcss discussion: https://github.com/parcel-bundler/lightningcss/issues/298
=> fix: unitless zero for `<angle>` values are allowed in CSS gradients

package.json, pnpm-lock.yaml, test/cases/example.out.css, test/cases/file-selector-button.out.css, test/cases/fullscreen.out.css, test/cases/keyframes.out.css, test/cases/placeholder-shown.out.css, test/cases/placeholder.out.css, test/cases/viewport.out.css
same as https://github.com/postcss/autoprefixer/pull/1481 but in reverse.
=> update test results for PostCSS 8.4.19

.github/CONTRIBUTING.md
This project uses pnpm for package management since 0d47b914998edd809718e5e3211d327157500865
=> doc: Fix package manager info

data/prefixes.js, lib/autoprefixer.js, lib/browsers.js, lib/supports.js, test/browsers.test.js, test/info.test.js, test/prefixes.test.js
In my case the time spent on require-ing `caniuse-lite` was reduced from ~300ms to ~100ms (tested on node 16.19.0).
=> Improves startup time by requiring specific caniuse files (#1492)

data/prefixes.js, test/autoprefixer.test.js, test/cases/backdrop.css, test/cases/backdrop.out.css
Before that, we added the `-wekbit-` prefix to Safari, which is not really needed.
Waiting for upstream PR: https://github.com/browserslist/caniuse-lite/pull/116
=> feat: `::backdrop` using `@mdn/browser-compat-data`

README.md
Brackets and Atom code editors have long since been deprecated and neither plugin has been updated in even longer. I think it makes sense to remove links to these.
REF:
- https://github.com/sindresorhus/atom-autoprefixer
- https://github.com/mikaeljorhult/brackets-autoprefixer
=> Remove deprecated browsers from README

lib/processor.js
```
Lightning CSS:    5 ms   (7.5 times faster)
Stylis:           6 ms   (6.3 times faster)
Autoprefixer dev: 29 ms  (1.2 times faster)
Autoprefixer:     36 ms
Stylecow:         204 ms (5.7 times slower)
```
- do cheap checks before expensive checks
- loop inside walkers instead of the other way around
=> improve performance
